[package]
name = "fixed_supply_token"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.26"
spl-token = { version = "=4.0.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
