name: Solana Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  security-audit:
    name: Cargo Audit & Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: |
          cargo audit --json > cargo-audit.json || true
          cargo audit > cargo-audit.txt || true
        continue-on-error: true

      - name: Run cargo clippy
        run: |
          cargo clippy --all-targets --all-features > clippy-output.txt 2>&1 || true
        continue-on-error: true

      - name: Build project
        run: cargo build --release
        continue-on-error: true

      - name: Run tests
        run: cargo test > test-output.txt 2>&1 || true
        continue-on-error: true

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spl-token-security-reports
          path: |
            cargo-audit.json
            cargo-audit.txt
            clippy-output.txt
            test-output.txt
          retention-days: 30

      - name: Display results summary
        if: always()
        run: |
          echo "=== Cargo Audit Summary ==="
          if [ -f cargo-audit.txt ]; then
            head -n 50 cargo-audit.txt
          fi
          echo ""
          echo "=== Clippy Summary ==="
          if [ -f clippy-output.txt ]; then
            head -n 50 clippy-output.txt
          fi
